### ISSUE TITLE
how to organize train datasets to start training?

### ISSUE THREAD

**Issue by Wangxinyu-qlz** [fuzailpalnak/building-footprint-segmentation#49]
I got 

> ValueError: num_samples should be a positive integer value, but got num_samples=0

, with:
```
Loader:

    root: ../datasets/
    image_normalizer: divide_by_255
    label_normalizer: binary_label
    batch_size: 2
```
in config.yml,
and my datasets(image & label) under the folder datasets/
Looking forward to your reply!
